disabled_rules:
  - identifier_name

excluded:
  - Pods
  - R.generated.swift

force_cast: error
force_try: error

file_length:
  warning: 500
  error: 1000

line_length:
  warning: 200
  error: 300

type_name:
  min_length: 1 # only warning
  max_length:
    warning: 50
    error: 60

function_parameter_count:
  warning: 4
  error: 6

cyclomatic_complexity:
  warning: 6
  error: 8
