disabled_rules:
  - force_try
  - force_cast
  - identifier_name
  - function_body_length

line_length:
  warning: 300
  error: 400

variable_name:
  min_length: 2

type_name:
  max_length:
    warning: 60
    error: 100
